### ISSUE TITLE
[BUG] Sadness chan not activating  5e v3.03

### ISSUE THREAD

**Issue by Wokeye27** [p4535992/foundryvtt-sadness-chan#1]
**Module Version:** v1.2.0
This module does not seem to activate on a 1 or 20, despite the settings being enabled. 

![image](https://github.com/p4535992/foundryvtt-sadness-chan/assets/77101610/ddb91276-9209-49a1-830c-f4d4f0de6c3d)

**Browser:**
chrome

**Foundry Version:** 
v11

**Game System:** 
5e v3.03

**Comment by p4535992** [comment]
Rewrite a bunch of code, now it should be working again with 1.2.1.
Let me know it.

**Comment by Wokeye27** [comment]
Looks like it's back - thanks! :)
